### ISSUE TITLE
Test different basepath scenarios

### ISSUE THREAD

**Issue by roll** [frictionlessdata/livemark#100]
# Overview

Currently, it works fine on localhost and https://livemark.frictionlessdata.io/ but there might be basepath problems e.g. on GIthub Pages without a custom domain.

**Comment by lwinfree** [comment]
here's my inadvertent test, which fails: https://github.com/lwinfree/test-livemark/issues/3

**Comment by roll** [comment]
Merged into https://github.com/frictionlessdata/livemark/issues/67
