### ISSUE TITLE
`pip install` downloads all versions

### ISSUE THREAD

**Issue by tresoldi** [frictionlessdata/livemark#137]
Installing with the recommended approach (`pip install livemark`) or a fresh virtual environment with `pip`, `setuptools`, and `wheel` up to date currently takes a long time, as the `frictionless` requirement is set with a star: https://github.com/frictionlessdata/livemark/blob/cd4200f143dfe6d77874de23e8c13a1cbeea0e08/setup.py#L48

Due to requirement settings in dependencies, it means that `pip` also downloads multiple versions of other libraries (`livemark` itself, `simpleeval`, etc.). In a non-fresh environment (e.g. one in which `frictionless` is already installed) it might lead to conflicts during installation, but I was not able to immediately reproduce it (maybe it depends on the order the packages are installed). The multiple downloads were reproduced both under the latest stable Ubuntu (with Python3.8) and WSL.

**Comment by roll** [comment]
Thanks @tresoldi! I will investigate
