### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/livemark#194]
# Overview

Hi @roll ,
first of all: this is great idea, a great product, thank you very much 🙏🙏🙏.

When I install it, I have this error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mkdocs-rss-plugin 0.17.0 requires Jinja2<3,>=2, but you have jinja2 3.0.2 which is incompatible.
jinja-markdown 1.200630 requires Jinja2~=2.11, but you have jinja2 3.0.2 which is incompatible.
datapackage-pipelines 2.2.6 requires python-dateutil<2.8.1, but you have python-dateutil 2.8.1 which is incompatible.
```
---

Does the only solution is to use virtualenv?

Thank you

Please preserve this line to notify @roll (lead of this repository)

**Comment by aborruso** [comment]
I have solved using [pipx](https://github.com/pypa/pipx)  that for me is the way I prefer to install "problematic" python modules.

livemark is really a great idea

**Comment by roll** [comment]
Thanks @aborruso !
