### ISSUE TITLE
URL Problems using `livemark build` on Windows 

### ISSUE THREAD

**Issue by gabrielbdornas** [frictionlessdata/livemark#205]
# Overview

I'm trying to build a [simple livemark](https://andrelamor.github.io/erros-validacao/) static site with a colleague and we're experiencing a very interesting problem due to operational systems differences, I believe. 

I'm using Linux ubuntu 20.04 and he's using Windows 10. 

When I run `livemark start` or `livemark build` on my ubuntu everything goes well, but when he does the same on windows it builds weird URLs. It appears that "/" is been changing to "%5C", as you can see [here](https://andrelamor.github.io/erros-validacao/..%5Cerros-validacao%5C001_metadados%5Cdatapackage-propriedades.html).

The Github source code could be found [here](https://github.com/Andrelamor/erros-validacao).

I also tried to run `livemark build --help` and see if there were some options related to windows construction and also to search for something in the documentation.

**Comment by roll** [comment]
Thanks @gabrielbdornas for flagging! I'll investigate

**Comment by roll** [comment]
Hi @aivuk, can you please take a look?

**Comment by aivuk** [comment]
@roll just pointed me that maybe the problem is how I'm using Python, I used after installing the Ubuntu applicaion for window https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview How are you using Python in the windows machine?

**Comment by aivuk** [comment]
Ok @roll, found out the problem and created a pull request. The problem is that outside Windows Services for Linux, as the Ubuntu app that I used in Windows, the os.path do not return POSIX compliant paths, they use backslash if it's running in windows. I changed the `get_relpath`to aways return a POSIX path with this slash \ instead of windows backslash /.
