### ISSUE TITLE
Release Livemark v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/livemark#35]
# Overview

We need to gather feedback for 1-2 months and then release:

- remove HTML/etc from version control
- implement "livemark clean"
- move built files (search/script/style) to "build" directory
- make the security note visible on all the doc screens (use NewsPlugin?)
- merge changelog/contribute into the docs
- remove "Not Found" page from SignsPlugin
- feature that adds a file name to a snippet output (often used in the docs)?
- rebase from `livemark merge` to some kind of `livemark test`?
- don't set width/height for the ImagePlugin by default (we need to use "unset" for now)
- signs/html descriptions/etc should take into account parent pages
- add custom CLI command to plugins by `Plugin.process_program`?
- **move `markdown` plugin and `livemark merge` to external plugins? (focus core on Markdown-to-HTML only?) !!!**
- release on PyPi
- release on Anaconda

**Comment by pwalsh** [comment]
@roll I'm commenting here as signing up for Discord to chat is a *friction-filled* experience :)

Nice work on livemark!

**Comment by roll** [comment]
Thanks, @pwalsh!

Long time no see =)

Livemark is a very raw ATM but I hope it has some promise. I'm looking forward to having something really lightweight for writing and publishing data-related stuff

**Comment by roll** [comment]
CLOSE for now (create an updated issue later)
