### ISSUE TITLE
Finish the documentation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/livemark#38]
# Overview

It needs to be finished for version 1

# Plan

- [ ] structure: logic, table, chart, script, markup, sidebars, widgets, config, plugins?
- [ ] improve current articles
- [ ] add new articles
- [ ] update the main (demo) page
- [ ] update the readme (features)

**Comment by lwinfree** [comment]
I'm happy to edit these - ping me when you need me :-)

**Comment by roll** [comment]
MERGED into #35
